#local environment 8080 is available outside container
localapplication:
  extends:
    file: docker-compose-base.yml
    service: application
  ports:
    - "8080:8080"
    
localnginx:
  extends:
    file: docker-compose-base.yml
    service: nginx
  ports:
  - "80:80"
  links:
    - localapplication:application
    
