local-application:
  extends:
    file: docker-compose-base.yml
    service: application
  ports:
    - "8080:8080"
    
local-nginx:
  extends:
    file: docker-compose-base.yml
    service: nginx
  ports:
  - "80:80"
  links:
    - local-application:application
    
